### ISSUE TITLE
Problem with Docker plugin

### ISSUE THREAD

**Issue by giancarloandroid** [thenativeweb/vagrant-node#3]
**Command**

`vagrant up`

**Result**

> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
>
> VagrantPlugins::DockerProvisioner::Config:
> * The following settings shouldn't exist: version

**Picture**
![selecao_744](https://cloud.githubusercontent.com/assets/8602136/25828955/aec08d12-3429-11e7-83f3-bd84e953bc70.png)

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊 

Apparently, according to the [Vagrant documentation](https://www.vagrantup.com/docs/provisioning/docker.html) there is no `version` setting any more, but it is still used in the [Vagrantfile](https://github.com/thenativeweb/vagrant-node/blob/c3f6134609e56277d720cc39a8d3cccdb38c7413/Vagrantfile#L38).

Would you mind doing the following things:

- Removing this setting, and verify whether things work again.
- Update [this line](https://github.com/thenativeweb/vagrant-node/blob/c3f6134609e56277d720cc39a8d3cccdb38c7413/Vagrantfile#L3) to the latest Vagrant version.
- Create a pull request with your changes.

This would be awesome 🎉😊

**Comment by goloroden** [comment]
Closed, since we don't actively maintain this repository any more (please consider it as deprecated).
